GET http://localhost:3003/api/blogs HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1heC1Gb3J3YXJkcyIsImlkIjoiNjUzMTkwNmFlMGY0YzkyZTk1YjNiMDZjIiwiaWF0IjoxNjk3NzUxNzYwfQ.RNMetJcSvViL43cEoxz8r2zDUWP0CBvk4jLp3s4_fKE